# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx3G -Dgson.disableReflectionAccessFilter=true
mod_version = 3.0.1-1.20.1
maven_group = com.cinemamod
archives_base_name = webdisplays

minecraft_version = 1.20.1
forge_version = 47.3.0
parchment_version = 2023.06.26
parchment_mappings = 2023.06.26-1.20.1
java_version = 17

fabric_loader_version = 0.14.19
fabric_api_version = 0.86.1+1.20.1
fabric_loom_version = 1.7.3

mod_id = webdisplays
mod_name = WebDisplays

porting_lib_version = 2.3.14+1.20.1
